### PR TITLE
Add debug to scripts in package.json

### PR DESCRIPTION
**Pull request by wokalski**

### CODE REVIEW

**Comment by ryyppy** [comment]
huh, interesting... are you using this feature a lot?

**Comment by wokalski** [comment]
Whenever I need to debug. What are other ways to debug next.js apps?

**Comment by wokalski** [comment]
Also feel free to close this PR if you want to keep this minimal and don't see it fitting. No offense taken :)

**Comment by ryyppy** [comment]
definitely useful for someone using vscode!

**Pull request merged**
